# Values are base64-encoded.
# To encode:  echo -n "yourvalue" | base64
# To decode:  echo "encodedvalue" | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: secure-share
type: Opaque
data:
  POSTGRES_USER:     cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB:       ZmlsZXNkYg==
  SECRET_KEY:        Y2hhbmdlLXRoaXMtc2VjcmV0LWtleS1pbi1wcm9kdWN0aW9u